[credentials]
valid_username = Admin
valid_password = admin123
invalid_username = wronguser
invalid_password = wrongpass
linkedin_username = swatikumari278@gmail.com
linkedin_password = Autumn@19

[env]
base_url_dev = https://www.linkedin.com/
#base_url_dev = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
base_url_qa = https://qa.orangehrm.example.com
base_url_prod = https://prod.orangehrm.example.com
active_env = dev

[timeouts]
implicit_wait = 10
explicit_wait = 20
page_load_timeout = 60

[testdata]
search_keyword = Dashboard
expected_title = OrangeHRM
